name: Database Migration

on: 
  push:
    branches: 
      - mysql_cicd_update1

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Docker network
      run: docker network create my-network

    - name: Start MySQL service
      run: |
        docker run -d \
          --name mysql-db \
          --network my-network \
          -e MYSQL_ROOT_PASSWORD=rootpassword \
          -e MYSQL_USER=testuser \
          -e MYSQL_PASSWORD=testpassword \
          -p 3306:3306 \
          mysql:8.0 \


    - name: Wait for MySQL to be ready
      run: |
        for i in {180..0}; do
          if docker exec mysql-db mysql -u root -prootpassword -e "SELECT 1" > /dev/null 2>&1; then
            break
          fi
          echo 'MySQL not ready yet...'
          sleep 1
        done
