
name: Database Migration

on: 
  push:
    branches: 
      - main
#    paths:
#      - 'dbscripts/**'

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --name mysql-db
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
            if docker exec mysql-db mysql -u testuser -ptestpassword -e "SELECT 1" > /dev/null 2>&1; then
                break
            fi
            echo 'MySQL not ready yet...'
            sleep 1
        done
    
    - name: Initialize Database Schemas and Grant Permissions
      run: |
        docker exec -i mysql-db mysql -u root -prootpassword < $GITHUB_WORKSPACE/init.sql

    - name: Run Liquibase migrations
      run: |
        LIQUIBASE_IMAGE="liquibase/liquibase"
        CHANGELOG_FILE="/liquibase/changelog/change.sql"
        URL_PREFIX="jdbc:mysql://mysql-db:3306/schema1"
        LIQUIBASE_LICENSEKEY="ABwwGgQUDvg+TwPk6F7EmjJg6gLEDLZj3OwCAgQAJJ5Jc0vNRRNw2+eZgro/35pG6BZu+MvhRd+vS9n5TzBhC0NcrYT8iO6BB90jcxfL/0mm0OIMe+Pxav/1lw9DjQo7b6Ubf5rnXo9yFnm2Szo8E2+A5x/Fdgg57ah2OGQFVJUD1kNrHNTSxeu0UN2yevASADRTfgiSC1FPo32X/B3LSr29ItF0qsTSbFONdbOFASSaAxI9ZAsIEG18WfZfSNMn0N7lRdRpQekxjGngepZiBY0S5I4lkL3mCikbWk8R7KfmATWUvVXpNP8tbSPCbAe/vRrgdX4QyakARO+jwddwinlMoF6afkBTDJ3OqQ9jFOMFeCb9EJPI608mlHjYVytQgQ1kwsEkdjM1lT+Dz8mtXc/XBagHFrgxutAVZrjQB7MxqasiLNpJEExO80oy6QWaEkTuMSjx29sfU77OYNV9GBUZ1iA3fny1lq98cMYGj1f57tJr8JFFZ/di8V0QJdx7t/7t3JjFPEFuubPGuv3RU47eR/MdFsi57H8dBxmaQQqxlNyxBilUUXWEm0E87gERv4QHgNh1g+RGXhcWN6YaQqFHyaufw0F1VGmDsgKK/C7drQdrXHC5HxCL5wQs2xhIdcDtZYW8goF7oud/cuJklq/YotaU+EEGoFYewGcOSSi7P1PlWnvgHvQkye7gh0W6dblgSoJv"
        DB_DRIVER="com.mysql.cj.jdbc.Driver"
                
        
            docker run --rm --network host -v $GITHUB_WORKSPACE/dbscripts:/liquibase/changelog $LIQUIBASE_IMAGE \
              --changeLogFile=${CHANGELOG_FILE} \
              --url="${URL_PREFIX}" \
              --username=testuser \
              --password=testpassword \
              --license-key=${LIQUIBASE_LICENSEKEY} \
              --driver=${DB_DRIVER} \
              connect
        

    - name: Display All Databases and Users Table Schema
      run: |
        echo "Listing all databases and 'users' table schema for each database:"
        for db in schema1 schema2 schema3 schema4 schema5 schema6 schema7 schema8 schema9 schema10; do
            echo "Checking database: $db"
            docker exec -i mysql-db mysql -u testuser -ptestpassword -e "USE $db; SHOW CREATE TABLE users;"
        done
